### ISSUE TITLE
Publish the SKY130 eFabless provided IO and Periphery cells

### ISSUE THREAD

**Issue by mithro** [google/skywater-pdk#9]
The SKY130 eFabless provided IO and Periphery cells library is currently empty, only a placeholder is currently provided.

The SKY130 foundry provided IO and Periphery cells library will be released at a future date.

Before these files are released access to these files is available through eFabless directly.

**Comment by RTimothyEdwards** [comment]
@mithro :  A reminder that the "efabless I/O" was a "quick & dirty hack" meant to get us something that we could tape out if we could not use the SkyWater I/O.  The cells in that library are not really approved for any use, and would be extremely ESD sensitive because they have no clamp circuits.  I have no intention of releasing this library except perhaps with strongly worded caveats.  Even then, it is more like a do-it-yourself project and probably should stay out of the official repository.
